name: i4

services:
  collector:
    build: ./collector
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "12001:12001"
    networks:
      - db-net
      - queue-net
      - api-net

  analyzer:
    build: ./analyzer
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - db-net
      - queue-net
  
  kafka:
    image: apache/kafka:3.8.0
    env_file: ./kafka/config.env
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --topic uploads --describe
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "9092:9092"
    expose:
      - "9092"
    networks:
      - queue-net
  
  kafka-init:
    image: apache/kafka:3.8.0
    depends_on:
      - kafka
    env_file: ./kafka-init/config.env
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      kafka-topics.sh --bootstrap-server kafka:9092 --list
      kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic uploads --replication-factor 1 --partitions 1
      kafka-topics.sh --bootstrap-server kafka:9092 --list
      "
    networks:
      - queue-net

  mongo:
    image: mongo:8.0.9
    command: mongod --quiet
    environment:
      MONGO_INITDB_USERNAME: "admin"
      MONGO_INITDB_PASSWORD: "admin"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - db-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/clients --quiet
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  db-net: {}
  queue-net: {}
  api-net:
    driver: bridge